vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
       meal_images:
           uri_prefix: /images/plat
           upload_destination: '%kernel.project_dir%/public/images/plat'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
